project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files: [
  {
    "source" : "docs/_build/gettext/*.pot",
    "translation" : "docs/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po",
  },
  {
    "source" : "docs/_build/gettext/**/*.pot",
    "translation" : "docs/locale/%locale_with_underscore%/LC_MESSAGES/**/%file_name%.po",
  },
]
